select * from Cidade
select * from Estado
select * from Pais
select * from TipoEndereco
select * from Genero
select * from Bandeira
select * from CartaoCredito
select * from Cliente
select * from Endereco